### ISSUE TITLE
Filtering Question

### ISSUE THREAD

**Issue by watersynth** [Wollnashorn/switch-mods#3]
Hi! Sorry for posting this here, but, if it's not too much trouble, can you briefly explain how you found the addresses?

Metroid Prime Remastered seems to have problems with anisotropic filtering as well.
See here: https://github.com/yuzu-emu/yuzu/issues/9800

Do you think it would be possible for that game to be fixed in a similar way?

Thanks!

**Comment by Wollnashorn** [comment]
Hi,

I will make a short write-up in the next days how I reverse engineered the instructions, but it involved quite a lot of steps. For example I've patched Yuzu first, so that it assigns texture samplers a debug label with the CPU address of the sampler descriptor ([TSCEntry](https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/textures/texture.h#L334)), so that I could see which sampler is which in RenderDoc and then set a watchpoint in the GDB debugger, that triggers when the descriptor memory is written.

> Do you think it would be possible for that game to be fixed in a similar way?

Yup, looks like it's the same thing. I suppose the game also doesn't use trilinear sampling, but harsh mipmap transitions with nearest neighbor mipmap filter. I assume in Ryujinx anisotropic filtering is forced for any texture sampler that accesses a texture with mip levels, unlike Yuzu, where this is only enabled for trilinear samplers. There is no perfect heuristic when or when not to add anisotropic filtering, so it is not like Yuzu doing worse or better here.

Anyway, one way to kind of fix this would be to **add a toggle in Yuzu's advanced graphics tab, that enables AF for all mipmap filters**. I'm saying "kind of" because trilinear + AF would still be better than bilinear + AF, but it should be indistinguishable at 16x.
